version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
